version: '2'
services:
  odoo14:
    image: poonlap/odoo-th:14.0
    command: -- --dev=all
    depends_on:
      - db
    ports:
      - "8014:8069"
    volumes:
      - ./addons:/mnt/extra-addons
      - ./config_v14:/etc/odoo
      - odoo-web-v14:/var/lib/odoo 
      # ./data:/var/lib/odoo # You need to change the permission of data folder to be writable by docker deamone.
  odoo13:
    image: poonlap/odoo-th:13.0
    command: -- --dev=all
    depends_on:
      - db
    ports:
      - "8013:8069"
    volumes:
      - ./addons:/mnt/extra-addons
      - ./config_v13:/etc/odoo
      - odoo-web-v13:/var/lib/odoo 
      # ./data:/var/lib/odoo # You need to change the permission of data folder to be writable by docker deamone.
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
volumes:
  odoo-db-data:
  odoo-web-v14:
  odoo-web-v13:
